// Song catalog + vocab glossary. Original lyrics, no copyrighted material.

const SONGS = [
  {
    id: "late-night-light",
    title: "Late Night Light",
    artist: "Mira Vance",
    album: "Paper Hours",
    year: 2024,
    duration: 158, // seconds
    bpm: 96,
    level: "B1",
    genre: "Pop",
    color: "#e8a87c",
    color2: "#c38d9e",
    // [time in s, line, optional CN translation]
    lyrics: [
      { t: 0,    en: "", cn: "" },
      { t: 8,    en: "We met where the river bends",                 cn: "我们在河流弯处相遇" },
      { t: 14,   en: "Nothing was said, we knew the rest",          cn: "什么都没说,其余的我们都懂" },
      { t: 21,   en: "Your hand in mine, the city hums",            cn: "你的手在我手中,城市在低吟" },
      { t: 27,   en: "A neon sign, a quiet sun",                    cn: "一抹霓虹,一颗安静的太阳" },
      { t: 34,   en: "You are the late night light",                cn: "你是深夜的光",                kind: "chorus" },
      { t: 40,   en: "The kind that softens everything",            cn: "把一切都温柔了的那种",        kind: "chorus" },
      { t: 47,   en: "You are the late night light",                cn: "你是深夜的光",                kind: "chorus" },
      { t: 53,   en: "I never want to lose this feeling",           cn: "我永远不想失去这种感觉",      kind: "chorus" },
      { t: 60,   en: "We laugh until the morning comes",            cn: "我们笑到天亮" },
      { t: 66,   en: "Your stories taste like honey",               cn: "你的故事甜如蜜" },
      { t: 73,   en: "I hold the moments in my chest",              cn: "我把这些瞬间藏在心口" },
      { t: 79,   en: "A diary made of laughter",                    cn: "一本由笑声写成的日记" },
      { t: 86,   en: "You are the late night light",                cn: "你是深夜的光",                kind: "chorus" },
      { t: 92,   en: "The kind that softens everything",            cn: "把一切都温柔了的那种",        kind: "chorus" },
      { t: 99,   en: "You are the late night light",                cn: "你是深夜的光",                kind: "chorus" },
      { t: 105,  en: "I never want to lose this feeling",           cn: "我永远不想失去这种感觉",      kind: "chorus" },
      { t: 112,  en: "If I could fold this night in half",          cn: "若我能将这夜对折",            kind: "bridge" },
      { t: 118,  en: "And keep you here a little longer",           cn: "把你多留一会儿",              kind: "bridge" },
      { t: 125,  en: "I'd give it all, I'd give it all",            cn: "我愿付出一切,付出一切",        kind: "bridge" },
      { t: 132,  en: "You are the late night light",                cn: "你是深夜的光",                kind: "chorus" },
      { t: 138,  en: "The kind that softens everything",            cn: "把一切都温柔了的那种",        kind: "chorus" },
      { t: 145,  en: "You are the late night light",                cn: "你是深夜的光",                kind: "chorus" },
      { t: 151,  en: "I never want to lose this feeling",           cn: "我永远不想失去这种感觉",      kind: "chorus" },
    ],
  },
  {
    id: "ocean-floor",
    title: "Ocean Floor",
    artist: "Daniel Reeve",
    album: "Slow Tide",
    year: 2023,
    duration: 187,
    bpm: 72,
    level: "B2",
    genre: "Indie",
    color: "#5b8ba0",
    color2: "#2e4a5e",
    lyrics: [],
  },
  {
    id: "coffee-on-tuesday",
    title: "Coffee on Tuesday",
    artist: "Pine Hollow",
    album: "Small Weather",
    year: 2025,
    duration: 142,
    bpm: 110,
    level: "A2",
    genre: "Folk Pop",
    color: "#d4a574",
    color2: "#8a6a3d",
    lyrics: [],
  },
  {
    id: "weightless",
    title: "Weightless",
    artist: "June Harbor",
    album: "Single",
    year: 2024,
    duration: 198,
    bpm: 88,
    level: "B1",
    genre: "Synth-pop",
    color: "#a78bfa",
    color2: "#5b3fa5",
    lyrics: [],
  },
  {
    id: "garden-state",
    title: "Garden State",
    artist: "The Letters",
    album: "Slow Bloom",
    year: 2022,
    duration: 224,
    bpm: 84,
    level: "C1",
    genre: "Indie Folk",
    color: "#7a9b76",
    color2: "#3d5a3a",
    lyrics: [],
  },
  {
    id: "sunday-window",
    title: "Sunday Window",
    artist: "Aria Sole",
    album: "Bloom Season",
    year: 2025,
    duration: 168,
    bpm: 102,
    level: "A2",
    genre: "Pop",
    color: "#f4a8a8",
    color2: "#a85858",
    lyrics: [],
  },
];

// Tap-to-define glossary. Word → entry.
const GLOSSARY = {
  bends: {
    word: "bend",
    pos: "verb / noun",
    ipa: "/bend/",
    cn: "弯曲;转弯处",
    def: "to curve, or the curved part of something (like a river or road).",
    examples: [
      { en: "The river bends to the east.", cn: "河流向东弯曲。" },
    ],
    level: "A2",
  },
  rest: {
    word: "the rest",
    pos: "noun phrase",
    ipa: "/ðə rɛst/",
    cn: "其余;剩下的部分",
    def: "the remaining part — what is left after something else.",
    examples: [
      { en: "I'll do the rest tomorrow.", cn: "剩下的我明天再做。" },
    ],
    level: "A2",
  },
  hums: {
    word: "hum",
    pos: "verb",
    ipa: "/hʌm/",
    cn: "低声哼唱;发出嗡嗡声",
    def: "to make a low continuous sound, like a city at night or a fridge.",
    examples: [
      { en: "The city hums all night.", cn: "城市整夜低鸣。" },
    ],
    level: "B1",
  },
  neon: {
    word: "neon",
    pos: "adjective",
    ipa: "/ˈniː.ɒn/",
    cn: "霓虹的",
    def: "very bright and glowing — like the colored signs in a city street.",
    examples: [
      { en: "A neon sign flickered above the door.", cn: "门上方一块霓虹灯在闪烁。" },
    ],
    level: "B1",
  },
  softens: {
    word: "soften",
    pos: "verb",
    ipa: "/ˈsɒf.ən/",
    cn: "使柔和;软化",
    def: "to make something less harsh, gentler, or kinder.",
    examples: [
      { en: "Music softens the room.", cn: "音乐让整个房间变得柔和。" },
    ],
    level: "B2",
  },
  honey: {
    word: "honey",
    pos: "noun",
    ipa: "/ˈhʌn.i/",
    cn: "蜂蜜;甜美的事物",
    def: "the sweet golden food bees make — also a metaphor for something pleasant.",
    examples: [
      { en: "Her voice was honey.", cn: "她的声音像蜂蜜一样。" },
    ],
    level: "A1",
  },
  chest: {
    word: "chest",
    pos: "noun",
    ipa: "/tʃɛst/",
    cn: "胸口;箱子",
    def: "the front of the body between neck and stomach — also a wooden box.",
    examples: [
      { en: "I felt warmth in my chest.", cn: "我感到胸口一阵暖意。" },
    ],
    level: "A2",
  },
  diary: {
    word: "diary",
    pos: "noun",
    ipa: "/ˈdaɪ.ə.ri/",
    cn: "日记;日记本",
    def: "a private book where you write down what happens each day.",
    examples: [
      { en: "She kept a diary every night.", cn: "她每晚都写日记。" },
    ],
    level: "A2",
  },
  laughter: {
    word: "laughter",
    pos: "noun",
    ipa: "/ˈlɑːf.tər/",
    cn: "笑声",
    def: "the sound or act of laughing.",
    examples: [
      { en: "The room was full of laughter.", cn: "房间里充满了笑声。" },
    ],
    level: "A2",
  },
  fold: {
    word: "fold",
    pos: "verb",
    ipa: "/foʊld/",
    cn: "对折;折叠",
    def: "to bend something over on itself, like paper or cloth.",
    examples: [
      { en: "Fold the letter in half.", cn: "把信对折。" },
    ],
    level: "A2",
  },
  half: {
    word: "in half",
    pos: "phrase",
    ipa: "/ɪn hæf/",
    cn: "对半;一半",
    def: "into two equal parts.",
    examples: [
      { en: "Cut the apple in half.", cn: "把苹果切成两半。" },
    ],
    level: "A2",
  },
  longer: {
    word: "longer",
    pos: "adverb",
    ipa: "/ˈlɒŋ.ɡər/",
    cn: "更久;更长",
    def: "for more time than before — comparative of 'long'.",
    examples: [
      { en: "Stay a little longer.", cn: "再多待一会儿。" },
    ],
    level: "A1",
  },
  quiet: {
    word: "quiet",
    pos: "adjective",
    ipa: "/ˈkwaɪ.ət/",
    cn: "安静的",
    def: "making little or no sound.",
    examples: [
      { en: "A quiet sun rose over the hills.", cn: "一颗安静的太阳从山上升起。" },
    ],
    level: "A1",
  },
  moments: {
    word: "moment",
    pos: "noun",
    ipa: "/ˈmoʊ.mənt/",
    cn: "瞬间;时刻",
    def: "a very short period of time.",
    examples: [
      { en: "Hold this moment.", cn: "记住这一刻。" },
    ],
    level: "A2",
  },
  hold: {
    word: "hold",
    pos: "verb",
    ipa: "/hoʊld/",
    cn: "握住;保持",
    def: "to have or keep in your hand or arms.",
    examples: [
      { en: "I'll hold the door.", cn: "我帮你扶着门。" },
    ],
    level: "A1",
  },
  taste: {
    word: "taste",
    pos: "verb",
    ipa: "/teɪst/",
    cn: "品尝;有...的味道",
    def: "to feel a flavor in your mouth, or to experience something figuratively.",
    examples: [
      { en: "Her stories taste like honey.", cn: "她的故事有蜜糖的味道。" },
    ],
    level: "A2",
  },
  stories: {
    word: "story",
    pos: "noun",
    ipa: "/ˈstɔːr.i/",
    cn: "故事",
    def: "an account of events, real or imagined.",
    examples: [
      { en: "Tell me a story.", cn: "给我讲个故事。" },
    ],
    level: "A1",
  },
  morning: {
    word: "morning",
    pos: "noun",
    ipa: "/ˈmɔːr.nɪŋ/",
    cn: "早晨",
    def: "the early part of the day, before noon.",
    examples: [
      { en: "We laugh until morning.", cn: "我们笑到天亮。" },
    ],
    level: "A1",
  },
  river: {
    word: "river",
    pos: "noun",
    ipa: "/ˈrɪv.ər/",
    cn: "河流",
    def: "a large natural stream of water.",
    examples: [
      { en: "We met by the river.", cn: "我们在河边相遇。" },
    ],
    level: "A1",
  },
  city: {
    word: "city",
    pos: "noun",
    ipa: "/ˈsɪt.i/",
    cn: "城市",
    def: "a large town.",
    examples: [
      { en: "The city is alive at night.", cn: "夜里的城市充满活力。" },
    ],
    level: "A1",
  },
  feeling: {
    word: "feeling",
    pos: "noun",
    ipa: "/ˈfiː.lɪŋ/",
    cn: "感觉;情感",
    def: "an emotional or physical sensation.",
    examples: [
      { en: "Don't lose this feeling.", cn: "别失去这种感觉。" },
    ],
    level: "A2",
  },
  lose: {
    word: "lose",
    pos: "verb",
    ipa: "/luːz/",
    cn: "失去;丢失",
    def: "to no longer have something.",
    examples: [
      { en: "I never want to lose this.", cn: "我永远不想失去这个。" },
    ],
    level: "A1",
  },
  give: {
    word: "give it all",
    pos: "phrase",
    ipa: "/ɡɪv ɪt ɔːl/",
    cn: "付出一切",
    def: "to put in maximum effort or to sacrifice everything.",
    examples: [
      { en: "I'd give it all for her.", cn: "我愿为她付出一切。" },
    ],
    level: "B1",
  },
  keep: {
    word: "keep",
    pos: "verb",
    ipa: "/kiːp/",
    cn: "保持;留住",
    def: "to continue to have or hold.",
    examples: [
      { en: "Keep this safe.", cn: "把这个保管好。" },
    ],
    level: "A1",
  },
  said: {
    word: "say (said)",
    pos: "verb",
    ipa: "/sɛd/",
    cn: "说",
    def: "past tense of 'say' — to speak words.",
    examples: [
      { en: "Nothing was said.", cn: "什么都没说。" },
    ],
    level: "A1",
  },
  knew: {
    word: "know (knew)",
    pos: "verb",
    ipa: "/njuː/",
    cn: "知道",
    def: "past tense of 'know' — to have information or understanding.",
    examples: [
      { en: "We knew the rest.", cn: "其余的我们都懂。" },
    ],
    level: "A1",
  },
  sign: {
    word: "sign",
    pos: "noun",
    ipa: "/saɪn/",
    cn: "标志;招牌",
    def: "a board or notice with information, often illuminated.",
    examples: [
      { en: "A neon sign glowed.", cn: "一块霓虹招牌发着光。" },
    ],
    level: "A1",
  },
  sun: {
    word: "sun",
    pos: "noun",
    ipa: "/sʌn/",
    cn: "太阳",
    def: "the star at the center of our solar system.",
    examples: [
      { en: "A quiet sun.", cn: "一颗安静的太阳。" },
    ],
    level: "A1",
  },
  hand: {
    word: "hand",
    pos: "noun",
    ipa: "/hænd/",
    cn: "手",
    def: "the part of the arm beyond the wrist.",
    examples: [
      { en: "Your hand in mine.", cn: "你的手在我手中。" },
    ],
    level: "A1",
  },
  met: {
    word: "meet (met)",
    pos: "verb",
    ipa: "/mɛt/",
    cn: "遇见",
    def: "past tense of 'meet' — to come together with someone.",
    examples: [
      { en: "We met by chance.", cn: "我们偶然相遇。" },
    ],
    level: "A1",
  },
  laugh: {
    word: "laugh",
    pos: "verb",
    ipa: "/læf/",
    cn: "笑",
    def: "to make sounds of happiness or amusement.",
    examples: [
      { en: "We laugh together.", cn: "我们一起笑。" },
    ],
    level: "A1",
  },
  comes: {
    word: "come",
    pos: "verb",
    ipa: "/kʌm/",
    cn: "来",
    def: "to move toward a place.",
    examples: [
      { en: "Until the morning comes.", cn: "直到清晨到来。" },
    ],
    level: "A1",
  },
  little: {
    word: "a little",
    pos: "phrase",
    ipa: "/ə ˈlɪt.əl/",
    cn: "一点点",
    def: "a small amount.",
    examples: [
      { en: "Stay a little longer.", cn: "再待一会儿。" },
    ],
    level: "A1",
  },
  light: {
    word: "light",
    pos: "noun",
    ipa: "/laɪt/",
    cn: "光",
    def: "the brightness that lets us see things.",
    examples: [
      { en: "The late night light.", cn: "深夜的光。" },
    ],
    level: "A1",
  },
  night: {
    word: "night",
    pos: "noun",
    ipa: "/naɪt/",
    cn: "夜晚",
    def: "the time of darkness between sunset and sunrise.",
    examples: [
      { en: "A long night.", cn: "漫长的一夜。" },
    ],
    level: "A1",
  },
  late: {
    word: "late",
    pos: "adjective",
    ipa: "/leɪt/",
    cn: "晚的;迟的",
    def: "after the usual or expected time.",
    examples: [
      { en: "It's getting late.", cn: "时间不早了。" },
    ],
    level: "A1",
  },
  kind: {
    word: "the kind that",
    pos: "phrase",
    ipa: "/ðə kaɪnd ðæt/",
    cn: "那种...的",
    def: "used to describe a particular type or sort.",
    examples: [
      { en: "The kind that makes you smile.", cn: "那种让你微笑的。" },
    ],
    level: "B1",
  },
  everything: {
    word: "everything",
    pos: "pronoun",
    ipa: "/ˈɛv.ri.θɪŋ/",
    cn: "一切;所有事物",
    def: "all things; all that exists.",
    examples: [
      { en: "It softens everything.", cn: "它让一切变柔和。" },
    ],
    level: "A1",
  },
  never: {
    word: "never",
    pos: "adverb",
    ipa: "/ˈnɛv.ər/",
    cn: "从不",
    def: "at no time; not ever.",
    examples: [
      { en: "I never want to leave.", cn: "我永远不想离开。" },
    ],
    level: "A1",
  },
  want: {
    word: "want",
    pos: "verb",
    ipa: "/wɒnt/",
    cn: "想要",
    def: "to wish for or desire.",
    examples: [
      { en: "I want this to last.", cn: "我希望这能持续下去。" },
    ],
    level: "A1",
  },
};

// User's saved vocab — start with a few pretend-saved entries
const INITIAL_SAVED = ["softens", "neon", "honey"];

// Profile / streak fixture
const PROFILE = {
  name: "Yuki",
  joined: "Mar 2025",
  level: "B1",
  streakDays: 23,
  weekProgress: [12, 8, 15, 22, 9, 18, 14], // minutes per day, M-S
  totalMinutes: 1284,
  songsLearned: 47,
  wordsKnown: 612,
  recent: [
    { song: "Late Night Light", artist: "Mira Vance", date: "Today", minutes: 14 },
    { song: "Garden State", artist: "The Letters", date: "Yesterday", minutes: 18 },
    { song: "Coffee on Tuesday", artist: "Pine Hollow", date: "Mon", minutes: 9 },
    { song: "Ocean Floor", artist: "Daniel Reeve", date: "Sun", minutes: 22 },
  ],
};

window.SONGS = SONGS;
window.GLOSSARY = GLOSSARY;
window.INITIAL_SAVED = INITIAL_SAVED;
window.PROFILE = PROFILE;
